spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/podong?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: podong
    password: 1234

mybatis:
  config-location: classpath*:mybatis-config.xml
  #data:
  #  mongodb:
  #    host: localhost
  #    port: 27017
  #    database: armsdb
#Upload 경로
repository:
  upload: /Users/podonghi/upload
  uploadGameImg: /Users/podonghi/upload/images
  uploadCompanyImg: /Users/podonghi/upload/company/images
  uploadRankImg: /Users/podonghi/upload/Rank/images
crawling:
  gameUrl: https://www.gamemeca.com/game.php
  gameCompanyUrl: https://www.gamemeca.com/game.php?rts=company
  gameRankUrl: https://www.gamemeca.com/ranking.php?rid=

batch:
  hs:
    useYn: N
    time: "* * 9 * * *"
    rankTime: "* * * * * *"
    doAuditTrail : false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true